//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Key { get; set; }
        public Nullable<int> EthAddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Product_Type { get; set; }
        public string Product_Detail { get; set; }
        public string Product_Address { get; set; }
        public byte IsActive { get; set; }
        public Nullable<int> NumberOfTransactions { get; set; }
        public string TransactionFromAddress { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public long TransactionID { get; set; }
        public long FirstTransactionID { get; set; }
        public string Serial_Num { get; set; }
    }
}
