//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEthAddress_V
    {
        public long Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Key { get; set; }
        public Nullable<int> EthAddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Product_Type { get; set; }
        public string Product_Detail { get; set; }
        public string Product_Address { get; set; }
        public byte IsActive { get; set; }
        public Nullable<int> NumberOfTransactions { get; set; }
        public string TransactionFromAddress { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int P_CreatedBy { get; set; }
        public System.DateTime P_CreatedDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string EthPublicKey { get; set; }
        public string EthPrivateKey { get; set; }
        public string RecoveryPhrase { get; set; }
        public string WalletAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime E_CreatedDate { get; set; }
        public int E_CreatedBy { get; set; }
        public long TransactionID { get; set; }
        public long FirstTransactionID { get; set; }
        public string Serial_Num { get; set; }
        public string TransactionHash_First { get; set; }
        public string TransactionHash_Now { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Detai { get; set; }
        public string Employee_email { get; set; }
        public string ErrorMessage { get; set; }
        public int IsDirectClaim { get; set; }
        public string Enter_ProductKey { get; set; }
        public string Enter_EthPrivateKey { get; set; }
        public string ImagePath { get; set; }
    }
}
