//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionID { get; set; }
        public string TransactionHash { get; set; }
        public long ProductID { get; set; }
        public int EthAddressID { get; set; }
        public string GasUsed { get; set; }
        public string BlockNumber { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public Nullable<decimal> EthAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int UserTypeID { get; set; }
        public string InputDataText { get; set; }
        public string InputDataHex { get; set; }
        public string ErrorMessages { get; set; }
    }
}
