//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public byte UserTypeID { get; set; }
        public string UserTypeName { get; set; }
        public string UserTypeDetail { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
